available_entities:
  block_content: block_content
  node: node
  path_alias: path_alias
  taxonomy_term: taxonomy_term
  user: user
  menu_link_content: menu_link_content
  comment: '0'
  contact_message: '0'
  content_moderation_state: '0'
  file: '0'
  shortcut: '0'
_core:
  default_config_hash: lcQIEazCoV3xb72H67GTKBEuGmqBDkWVA6bm4Gb22NA
